#!/usr/bin/env python3
"""Sync a review-friendly finalized folder from the current T1 annotation bundle."""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = REPO_ROOT / "data" / "finalized"

SOURCE_FILES = [
    ("data/raw/t1_mprage.nii.gz", "source/t1_mprage_original.nii.gz"),
    ("data/raw/t1_mprage.json", "source/t1_mprage_original.json"),
    ("data/working/itksnap/t1_conformed.nii.gz", "source/t1_conformed_freesurfer.nii.gz"),
]

GENERATED_REVIEW_FILES = [
    ("data/working/itksnap/auto_seed_segmentation.nii.gz", "generated_review/candidate_auto_seed_segmentation.nii.gz"),
    ("data/working/itksnap/blank_segmentation.nii.gz", "generated_review/blank_segmentation.nii.gz"),
    ("data/working/itksnap/labels.tsv", "generated_review/labels.tsv"),
    ("data/working/itksnap/points.tsv", "generated_review/points.tsv"),
    ("data/working/itksnap/itksnap_label_descriptions.txt", "generated_review/itksnap_label_descriptions.txt"),
    ("annotations/localization/itksnap-export-manifest.json", "generated_review/itksnap-export-manifest.json"),
    ("annotations/localization/itksnap-export-review.md", "generated_review/itksnap-export-review.md"),
    ("annotations/localization/t1-localization-review.md", "generated_review/t1-localization-review.md"),
    ("annotations/structures/t1-targets.localized.draft.json", "generated_review/t1-targets.localized.draft.json"),
]

GENERATED_REVIEW_DIRS = [
    ("data/working/itksnap/full_gyrus_masks", "generated_review/full_gyrus_masks"),
    ("data/working/itksnap/rough_support_masks", "generated_review/rough_support_masks"),
]


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def relative(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(REPO_ROOT.resolve()))
    except ValueError:
        return str(path)


def copy_file(src_relative: str, dest_relative: str, output_dir: Path) -> dict[str, Any]:
    src = REPO_ROOT / src_relative
    dest = output_dir / dest_relative
    if not src.exists():
        raise FileNotFoundError(src)
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dest)
    return {
        "source": relative(src),
        "destination": relative(dest),
        "bytes": dest.stat().st_size,
        "sha256": sha256(dest),
    }


def copy_dir(src_relative: str, dest_relative: str, output_dir: Path) -> dict[str, Any]:
    src = REPO_ROOT / src_relative
    dest = output_dir / dest_relative
    if not src.exists():
        raise FileNotFoundError(src)
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(src, dest)
    files = sorted(path for path in dest.rglob("*") if path.is_file())
    return {
        "source": relative(src),
        "destination": relative(dest),
        "fileCount": len(files),
        "bytes": sum(path.stat().st_size for path in files),
    }


def write_readme(output_dir: Path) -> None:
    text = """# Finalized Review Bundle

This folder is the review-friendly handoff area for the current annotated T1 project.

## Open In ITK-SNAP

Use this pair for reviewing the current generated candidate annotations:

```text
source/t1_conformed_freesurfer.nii.gz
generated_review/candidate_auto_seed_segmentation.nii.gz
```

The raw original T1 MPRAGE is also copied here:

```text
source/t1_mprage_original.nii.gz
source/t1_mprage_original.json
```

## Folder Meaning

- `source/`: original T1 MPRAGE plus FreeSurfer-conformed T1 used by the labelmaps.
- `curation/`: human-editable target JSON and curation spreadsheets. The sync script does not overwrite this folder.
- `generated_review/`: generated candidate annotations and review tables. This folder is regenerated by `scripts/sync_finalized_review_bundle.py`.
- `accepted_annotations/`: put manually reviewed, accepted labelmaps here. The sync script does not overwrite this folder.

The generated labelmaps are review candidates, not manually accepted final labels yet.
"""
    (output_dir / "README.md").write_text(text, encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output_dir = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "accepted_annotations").mkdir(parents=True, exist_ok=True)
    (output_dir / "curation").mkdir(parents=True, exist_ok=True)

    manifest: dict[str, Any] = {
        "version": "0.1.0",
        "kind": "finalized_review_bundle",
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "sourceFiles": [],
        "generatedReviewFiles": [],
        "generatedReviewDirs": [],
        "acceptedAnnotationsDir": relative(output_dir / "accepted_annotations"),
        "curationDir": relative(output_dir / "curation"),
    }

    for src, dest in SOURCE_FILES:
        manifest["sourceFiles"].append(copy_file(src, dest, output_dir))
    for src, dest in GENERATED_REVIEW_FILES:
        manifest["generatedReviewFiles"].append(copy_file(src, dest, output_dir))
    for src, dest in GENERATED_REVIEW_DIRS:
        manifest["generatedReviewDirs"].append(copy_dir(src, dest, output_dir))

    write_readme(output_dir)
    manifest_path = output_dir / "finalized-review-manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    print(f"Wrote {relative(manifest_path)}")
    print(f"Source files: {len(manifest['sourceFiles'])}")
    print(f"Generated review files: {len(manifest['generatedReviewFiles'])}")
    print(f"Generated review directories: {len(manifest['generatedReviewDirs'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
